### ISSUE TITLE
Some random bugs

### ISSUE THREAD

**Issue by Lexx2k** [alexbatalov/fallout2-re#1]
- [x] AP display in character generation doesn't refresh when changing agility.
- [x] Can't right click until combat cursor in combat mode. (worked when unarmed tho)
- [x] Critter speed in combat is not influenced by combat speed in the settings.
- [x] Villagers in Arroyo are scared of me and when talking to them float Error. Maybe something up with reading the karma / reputation values.

**Comment by alexbatalov** [comment]
1. Fixed.
2. Not sure what you mean, can you elaborate? I have right click (switching between moving and pointing) working both in combat and non-combat modes.
3. Fixed a small error in fps calculation routine. What is the critter by the way?
4. Cannot reproduce. Please attach save game.

**Comment by Lexx2k** [comment]
2. When in combat, all I can do is switch between yellow and hex cursor. I can't swap to the aiming cursor and am forced to click the weapon icon. Used the spear in the beginning of the game. In unarmed combat it works fine.
3. Saw it with the ants and scorpions in the temple. Blindly assuming it is the case for all critters.
4. Here is my savegame:
[SLOT01.zip](https://github.com/alexbatalov/fallout2-re/files/8626151/SLOT01.zip)

Everyone in Klamath is running away / starting combat with me as well. Must have something to do with karma/reputation.

/Edit: 
- [x] Found another issue. When pressing F5 for the loading screen and then get out of it with ESC, the quicksave screen opens.

**Comment by Lexx2k** [comment]
PS: I understand the goal of this project, but I think it would draw more attention if a form of the high-res patch is implemented asap. For almost all players it's a part of the default experience anyways by now. Especially since most people have a widescreen monitor.

**Comment by alexbatalov** [comment]
I cannot open your save game. re gracefully handled that with "Unable to load game", while original binary crashed (which I guess is bug itself given the goal). Do you have patches applied to your data? Can you load this savegame with the original binary?

**Comment by Lexx2k** [comment]
No patches, it's pretty much "empty" Fo2 1.02 with no patch000.dat etc. I can load the file with the normal exe (critters are not hostile then).

**Comment by alexbatalov** [comment]
I'm not sure why but we have differences. Your savegame contains 695 global variables, mine is 696. When I manually decrease number of variables your savegame loads perfectly fine, critters are not hostile. Please start a new game with the normal exe, do not move your character, save immediately. Do the same with re exe. Send me both versions so I can compare them.

**Comment by Lexx2k** [comment]
Yes, I have 695 GVARs in my vault13.gam in the master.dat https://pastebin.com/znPdybrP

Here are the savegames:
[SAVEGAME.zip](https://github.com/alexbatalov/fallout2-re/files/8627688/SAVEGAME.zip)

I also noticed that in vanilla Fo2, I can type uppercase and lowercase when saving the game, in your exe it is all uppercase. 

/Edit: I think you have a patched version with patch000.dat - I crosschecked with my other installation and this one has 696 GVARs in the vault13.gam file (inside the patch000.dat).

/Edit2: And now windows defender has flagged your exe file as bad and quarantined it.

/Edit3: Started a new game with the patch000.dat, but everyone is still running away from me. If I load the savegame with the vanilla exe file, everything works fine.

**Comment by alexbatalov** [comment]
I've checked your save games, but still cannot reproduce your problem. My vault13.gam have 696 vars in master.dat, and it's identical to the one extracted from patch000.dat, so removing the latter from the game directory does not help. To reiterate if I manually adjust number of variables your save games are loading fine, civilians do not run away. The reason is somewhere else. Please post your karmavar.txt, mine is the same master.dat and patch000.dat.

**Comment by Lexx2k** [comment]
There is no change to those either. I tested again with the vanilla GOG version of Fo2 yesterday, and there I have exactly the same issue. With the Fallout2.exe everything works fine, but with fallout2-re.exe it goes mad. 

![scr00002](https://user-images.githubusercontent.com/4844938/167244173-dc045c2c-cf1c-4c24-b327-71d2cdffeb53.png)

**Comment by Lexx2k** [comment]
The issue has something to do with local variables. I tested with acvillgr script. For some reason, this returns true:
`if (((local_var(LVAR_Hostile) == 2) or (local_var(LVAR_Personal_Enemy) == 1)) and (obj_can_see_obj(self_obj,dude_obj))) then begin`

This returns false:
`if (((local_var(LVAR_Personal_Enemy) == 1)) and (obj_can_see_obj(self_obj,dude_obj))) then begin`
So the issue has explicitly to do with LVAR 5 (LVAR_Hostile). If I remove that one from the condition, everything is fine.

For some reason the game only reads up to 4 LVARs for me? Thing is, if I check LVAR_Hostile on map enter, it returns 0. So why will == 2 return true in critter_proc? It is not changed anywhere else in script -- in critter_proc the game simply reads it as true.

**Comment by alexbatalov** [comment]
Post your savegame from GOG version.

**Comment by Lexx2k** [comment]
[SAVEGAME.zip](https://github.com/alexbatalov/fallout2-re/files/8644694/SAVEGAME.zip)

I did more tests. The issue has nothing to do with the LVAR number. I tried with local_var(1) instead of LVAR_Hostile and the same effect happens. The issue lies with the condition for whatever reason.

/Edit: This code works fine.
`if (local_var(LVAR_Hostile) == 2 and obj_can_see_obj(self_obj,dude_obj)) then begin`

But as soon as I am adding a "or" condition, it returns true even if it should not.

/Edit2: Another test, in map_enter_p_proc
This returns false:
```
   if (local_var(LVAR_Hostile) == 2) then begin
      display_msg("and i ooop");
   end
```

This returns true:
```
   if (local_var(LVAR_Hostile) == 2) or (local_var(LVAR_Personal_Enemy) == 1) then begin
      display_msg("and i ooop");
   end
```

Both variables, LVAR_Hostile and LVAR_Personal_Enemy are 0.

**Comment by alexbatalov** [comment]
Missing breaks are to blame. In release builds compiler optimized away entire case block because it ends with `__assume(0)`. There are no such optimizations in debug builds so I didn't notice it. Can we close this?

**Comment by ghost2238** [comment]
> Missing breaks are to blame. In release builds compiler optimized away entire case block because it ends with `__assume(0)`. There are no such optimizations in debug builds so I didn't notice it. Can we close this?

Makes sense. I couldn't reproduce the issue with the same saves as Lexx locally when using debug build directly from source. 

Please consider accepting #6 to make it easier for Lexx (and a wider audience, too) to test the latest code changes. At the moment I have to supply him with builds.

**Comment by Lexx2k** [comment]
Tested latest build, it is working now. 👍
