### ISSUE TITLE
Critters walking through locked doors

### ISSUE THREAD

**Issue by Lexx2k** [alexbatalov/fallout2-re#13]
See savegame:
[SLOT01.zip](https://github.com/alexbatalov/fallout2-re/files/8646630/SLOT01.zip)

Just walk away, sulik will follow through the door.

**Comment by ghost2238** [comment]
I think this may be related or the cause: https://github.com/alexbatalov/fallout2-re/blob/main/src/animation.c#L1429-L1431

a1 is the critter and a2 is the door/object if I'm reading the code correctly. But objectIsLocked is called with a1.
