### ISSUE TITLE
Music / sfx stops

### ISSUE THREAD

**Issue by Lexx2k** [alexbatalov/fallout2-re#26]
Every once in a while, either the music stops in my game, or certain sound effects won't play anymore (reloading weapons, missing hits, clicking on buttons). 

Bad news is, I haven't found a 100% repro yet, so don't know what is causing this. However, it happens quite often and gets fixed with reloading a savegame.

**Comment by alexbatalov** [comment]
Last time I saw this one was because some sound did not end properly ending up filling all 4 sound slots. Apparently there is other failing filler/decoder. Don't expect a quick fix on that one.
