### ISSUE TITLE
Savegame corruption

### ISSUE THREAD

**Issue by Lexx2k** [alexbatalov/fallout2-re#30]
[SLOT01.zip](https://github.com/alexbatalov/fallout2-re/files/8660224/SLOT01.zip)

Use lockpicking on the door to the armory. You will be spotted and combat starts. Now reload the savegame -- the game will crash and the savegame is now corrupted. 

Interesting side note: If you make multiple saves in the same location (e.g. in slot 1 and slot 2), both saves will get corrupted and won't load anymore.

**Comment by alexbatalov** [comment]
Cannot reproduce this one. I've tried to use lockpick via context menu, via skilldex, and opening without using lockpick. The first attempt does nothing. On the second try it starts combat. Reloading/exiting to main menu/loading same slot works as expected. The same behaviour is seen in vanilla exe. Tried both debug and release versions. Probably there is a bug in other save game or data folder is not cleared correctly. Manually delete `data/maps` and `data/proto`. If it's still reproduced, send your entire `data/savegame`.

**Comment by Lexx2k** [comment]
Great, now I can't reproduce it either with that save. It's the third time that I corrupted my saves, and I had high hopes that I've found a reliable way to reproduce it ... looks like it isn't.

**Comment by alexbatalov** [comment]
Send corrupted savegame so I can check where it fails.

**Comment by Lexx2k** [comment]
This one is broken:
[SLOT02.zip](https://github.com/alexbatalov/fallout2-re/files/8661138/SLOT02.zip)

**Comment by alexbatalov** [comment]
I'm not sure this is fixed, so let's keep it open for a while. The problem is with saving objects marked with special flag. This flag is set when objects delete themselves via scripting.
