### ISSUE TITLE
Getting low amount of XP for stealing, also possibly chance to be detected is lower

### ISSUE THREAD

**Issue by emxd** [alexbatalov/fallout2-re#41]
savegame -> https://icedrive.net/s/a9CgGiQ5iT4zx1Aavyi3ugyVNRz4

If I do 4 successful steal attempts in vanilla I get 100xp, in F2RE I'm getting only 40xp (the formula in RE seems to be just a simple multiplication).

Also it feels like I'm having a much easier time stealing/planting items. I do get detected occasionally, but it feels like it happens less often. Possibly there's some problem with the function where the subject of theft tries to detect if anyone is stealing from him?

Edit: Yep, I gave my character 300 steal skill and I can steal/plant the minigun with no problems.

**Comment by alexbatalov** [comment]
Nice catch
