### ISSUE TITLE
Crash when using examine on damaged critter

### ISSUE THREAD

**Issue by ghost2238** [alexbatalov/fallout2-re#5]
Repro:
1. Enter combat.
2. Injure enemy a few HP until they are no longer "unhurt".
3. Try to examine the critter, the game will crash with the message "Error: Can't find msg num!"

Crash is somewhere in [proto_instance.c](https://github.com/alexbatalov/fallout2-re/blob/main/src/proto_instance.c) 

Edit: Noticed that there were multiple possible code spots for crash.
Edit2: It's here: https://github.com/alexbatalov/fallout2-re/blob/main/src/proto_instance.c#L367-L371 
Nitpicky sidenote, "hitPoitsMessageListItem" should probably be "hitPoin**t**sMessageListItem"

Using a clean Fallout 2 install from steam, with a local build that includes https://github.com/alexbatalov/fallout2-re/commit/c7c6a4b7e690a03545255f8649062879d1aa6d58

Save: [SLOT01.zip](https://github.com/alexbatalov/fallout2-re/files/8642357/SLOT01.zip)

**Comment by alexbatalov** [comment]
Thanks for report
