### ISSUE TITLE
Walkthrough

### ISSUE THREAD

**Issue by alexbatalov** [alexbatalov/fallout2-re#58]
Hey guys, please let me know how far did you get in walkthrough and speedrun. Once we have a couple of confirmations that it's possible, I guess we'll move on to Fallout 2 Community Edition.

**Comment by Lexx2k** [comment]
I have the car and visited every location. Didn't play further than that, though - I like Fo1 more than 2. All bugs I've found on the way seem to have been addressed now.

However, I did not check if any of the perks and skill mechanics are working as expected. Considering there have been many bugs related to tiny issues, I wouldn't be surprised if half the perks are also buggy. :>

What are you planning for the "Community Edition"? Personally I think all the latest Sfall stuff needs to be ported over -- it has many crucial bug fixes, features, and modding capabilities. Basically, if this version here won't support the same stuff that Sfall does right now (script commands, etc), it will be very hard for existing mods to consider switching away from Sfall.

**Comment by alexbatalov** [comment]
That's very cool, thank you for you time. Making fallout1-re will take about 2 months, once fallout2-re is done. That's one of the reasons I need it to be free of any changes. However I'm not sure if there is a need for Fo1 because of Et Tu.

As for the "Community Edition", you are absolutely right about Sfall. Incorporating it's functionality and features should be a breeze. I'm also interested in porting it to macOS. Up next I think we gonna drop SSL in favor of Lua.

**Comment by Lexx2k** [comment]
I'm biased of course, but with ettu a fo1-re isn't necessary, imo. Even right now we can pretty much do everything we want with it, all the Fo2 features are working, etc. no big deal. Porting all the bugfixes, etc. back to Fo1 will be quite some work and likely requires lots of rewrites again. I think it's a waste of time, since the Fo2 engine is simply superior right out of the box.

**Comment by wipe2238** [comment]
> drop SSL in favor of Lua

Oh gods, don't... not as a _main_ goal at least.

I'd much more welcome approach like WeeChat have, which is: making stable **C** api for engine<->scripts communication, and once it's done said api is used to implement new scripting languages(s). Be it Lua, AngelScript, Perl, Python, whatever. As SSL is out there anyway, it can be a tool which helps to make sure C scripting api is feature complete.

I'd really don't want to loose any future improvements (both coming from SFall, as well as completely new things) in vanilla runs, or EtTu, or any other big SSL mod out there. I get it's kinda bad time and place to talk about stuff like that yet, but better too early than too late, heh :S

**Comment by Risu** [comment]
I would appreciate the linux build at some point (it would urge me to join the bug hunt).

**Comment by JanSimek** [comment]
+1 for the linux support in the community edition. I run fallout2-re under QEMU but I have a problem with debugging. I am trying to figure out why I am not losing any health while poisoned but when Visual Studio reaches a breakpoint I cannot Alt+Tab out of the game. Is there any trick to it or does that not happen under "native" Windows 10?

As for the scripting, I would love to use Lua to mod Fallout! However, I am quite sure it will alienate most of the community members who spent the past two decades working with SSL and Sfall. Although, SSL scripts are relatively simple and have a rigid structure so perhaps it could be possible to write a transpiler from SSL -> Lua and add the missing Sfall functions.

**Comment by emxd** [comment]
I finished the game, I'd say 97%+ of the content. I never really had any problem with content parsing or with the quests. If there were bugs with quests, the bugs were also present in vanilla. 

I tried 99% of the perks and they all worked, I didn't try the explorer types, they're kind of difficult to ascertain whether they're actually increasing the probability of special random encounters. Also stonewall... these kind of probabilistic perks are just easier to check via code.

As always I might have missed something, but from my point of view it's indistinguishable from vanilla.

**Comment by alexbatalov** [comment]
@emxd with all this Community Edition stuff I didn't have a chance to thank you. You did incredible job finding even the smallest discrepancies in no time. Before releasing Reference Edition I estimated validation and fixing decompilation issues would take about 3 months, thanks to you and of course @Lexx2k it only took a couple of weeks. Hope to see your ideas and considerations for Community Edition so we can make this game better than ever.

**Comment by burner1024** [comment]
I'm not even sure what do you mean by "drop SSL". SSL is just a source for INT. You can't drop INT support, it's integral to Fallout.
