### ISSUE TITLE
A couple of more bugs

### ISSUE THREAD

**Issue by emxd** [alexbatalov/fallout2-re#60]
- Hakunin movies don't start -> [SLOT08.zip](https://github.com/alexbatalov/fallout2-re/files/8693494/SLOT08.zip)
 if you sleep for a day in that savefile, in vanilla you get a Hakunin, in RE you don't

- weapon range and AC in inventory incorrectly displayed -> https://imgur.com/a/TveEeOM

- you don't get xp for killing critters with explosives -> [SLOT02.zip](https://github.com/alexbatalov/fallout2-re/files/8693507/SLOT02.zip)
In vanilla I get ~350xp for killing the Shi leader scientist, in RE nothing.

**Comment by Lexx2k** [comment]
I saw all the hakunin videos while traveling around on the worldmap.

**Comment by emxd** [comment]
Well, can you confirm that there's no video in that savefile? Might be something specific there.

Edit: the whole thing is rather strange, the first Hakunin video is somewhere around ~20th of October. That savefile is however ~30th August. But if I load that savefile I'm getting a Hakunin in vanilla, but not in RE. I only noticed that video because I'm playing semi parallelly. I also did a clean install.

The 20th of October Hakunin is triggered in RE.

That savefile was produced in RE though. I'll try to do a speedrun there purely in vanilla.

**Comment by emxd** [comment]
This time I got to Enclave by August 23th, purely vanilla, slept for a day and I got a Hakunin. No video if I then tried the vanilla savefile in RE. There seems to be something Enclave specific where if you sleep there, you get the video irrespective of the date.
