### ISSUE TITLE
Conversation not triggered

### ISSUE THREAD

**Issue by emxd** [alexbatalov/fallout2-re#80]
[SLOT04.zip](https://github.com/alexbatalov/fallout2-re/files/8714172/SLOT04.zip)

When exiting out of the V15 elevator there's a guard that asks you to identify yourself in vanilla. In RE this is not triggered.

**Comment by alexbatalov** [comment]
Cannot reproduce this one. Conversation starts both in vanilla and re.

**Comment by emxd** [comment]
Just to make sure we're talking about the same thing since I worded it lazily.
Vanilla: https://streamable.com/o1vik4
RE: https://streamable.com/81x5r6

In vanilla my character is detected and the conversation starts automatically. In RE I'm not detected and I have to start it manually. I assumed that there's some problem with detection. I tried it on 2 computers and it always behaved the same.

**Comment by c6-dev** [comment]
I couldn't reproduce this either, conversation started like your vanilla video is showing. I do recall something like that happening in my vanilla playthroughs though.

**Comment by alexbatalov** [comment]
This is only reproducible in release builds. Optimization eats up bool, so when it's put on the stack many bad things happen. I guess using bool instead of mere int was not one of my great ideas.
