### ISSUE TITLE
Some buttons blacked out

### ISSUE THREAD

**Issue by emxd** [alexbatalov/fallout2-re#83]
[SLOT10.zip](https://github.com/alexbatalov/fallout2-re/files/8715296/SLOT10.zip)

For a longer time I noticed this but I've struggled with how to reproduce it, but I think I know now...

open pipboy -> open status -> open some city, let's say Redding -> click on the back button -> buttons are blacked out

![fallout2-re_LnJFHEpZVq](https://user-images.githubusercontent.com/6156912/169014892-213e8e3b-edad-415a-8efe-a4092ef6efe1.png)
![fallout2-re_rEb6c9tEGn](https://user-images.githubusercontent.com/6156912/169014923-60b9e1f9-0e10-4f5b-bda1-908528aecfce.png)

**Comment by emxd** [comment]
Hmm, on a new game this doesn't happen. Maybe it happens when there are too many entries?...

**Comment by emxd** [comment]
[SLOT04.zip](https://github.com/alexbatalov/fallout2-re/files/8716469/SLOT04.zip)
On this savefile if you open pipboy -> status -> hubologist teachings -> click through all 7 pages -> done; even more GUI elements are blacked out (the big attack mode box).

Strangely enough, if you open that save in vanilla and read through the hubologist teachings, the Skilldex button becomes blacked out. So to some extent, this also happens in vanilla?

Tried it in sfall 4.3.4 and there were no problems with the GUI...

**Comment by NovaRain** [comment]
The "black Skilldex button" was a vanilla bug, triggered by having many active quests and holodisk entries.

**Comment by emxd** [comment]
That puts things into perspective, although in RE it's more common than just the skilldex button. Arguably, if possible, a deviation could be made from vanilla and fix it completely? I've had it for a 1/2 of the game and the newest one with the attack mode button is quite jarring.
![fallout2-re_72ME9VbAq1](https://user-images.githubusercontent.com/6156912/169103825-bb993870-161c-46ad-abb8-3e910391511e.png)
