### ISSUE TITLE
Community Edition

### ISSUE THREAD

**Issue by alexbatalov** [alexbatalov/fallout2-re#87]
Hey folks. With fantastic input from @Lexx2k and @emxd as testers a handful of bugs were fixed, which makes Reference Edition closer to it's goal with every single commit. While some functionality still missing, the bugs I've seen so far were pretty easy to fix (rather than spot them). I see no reason why shouldn't we start Community Edition right away. Here is [separate](https://github.com/alexbatalov/fallout2-ce) project for it. Starting with conversion to SDL, it's now possible to run the game in a windowed mode at arbitrary resolution (compatible with in f2_res.ini), which paves a way to integrating HRP and Linux. Hope to bring more people in to integrate sfall, while I'm fixing bugs in RE.

**Comment by JanSimek** [comment]
Do you plan to keep the source code in C or would you consider porting it to C++?

**Comment by alexbatalov** [comment]
There is no point in keeping it C, we'll convert it to C++.

**Comment by alexbatalov** [comment]
Done. There are way more warnings during compilation, but it's C++ already.
